from setuptools import setup, find_packages

setup(
    name="seed-stage-based-messaging",
    version="0.1",
    url='http://github.com/praekelt/seed-stage-based-messaging',
    license='BSD',
    author='Praekelt Foundation',
    author_email='dev@praekeltfoundation.org',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django==1.10.4',
        'djangorestframework==3.5.3',
        'dj-database-url==0.4.1',
        'psycopg2==2.6.2',
        'raven==5.32.0',
        'django-filter==1.0.1',
        'dj-static==0.0.6',
        'celery==3.1.24',
        'django-celery==3.1.17',
        'redis==2.10.5',
        'pytz==2016.10',
        'requests==2.12.3',
        'go-http==0.3.0',
        'drfdocs==0.0.11',
        'seed-services-client>=0.9.0',
        'croniter==0.3.13',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Framework :: Django',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
