# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageset',
            name='content_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice')], default='sms', max_length=20),
            preserve_default=False,
        ),
    ]
